### ISSUE TITLE
Re-send entities on chunk expansion to prevent invisible players / mobs / entities (i.e. arrows)

### ISSUE THREAD

**Issue by mibby** [Kugge/BestViewDistance#28]
BestViewDistance compiled as of commit https://github.com/Kugge/BestViewDistance/commit/8e335e8d61ba77dd4e1c83dfda28e23ac98771f9 with all 5 active pull requests as of 4/8.
Paper dev (Spigot 1.13.2)
ProtocolSupport dev 374

Config
https://paste.ubuntu.com/p/pMH6kFr4RG/

Spigot View Distance: 3

I've been receiving reports of invisible players, mobs, and entities (such as shooting arrows) ever since adding BVD. If it's not done so already, can entities be re-sent to the client when the view distance is expanded to prevent invisible issue?

**Comment by graywolf336** [comment]
I've noticed this too, it's very evident when you login. I can replicate it super easily by starting up the server, logging in, and then logging in with another account. The first user that is logged in won't be visible to the second user.

**Comment by graywolf336** [comment]
@mibby So, I believe I have resolved this. 🙈 

The commit is: https://github.com/graywolf336/BestViewDistance/commit/4f522cc3cafe9a11aa061ec64c3e0cc4514b1ffe

The apparent issue was that there is a bug somewhere, whether in paper or Minecraft, that if you change the view distance as soon as a player logs in the client has trouble getting/showing entities. Due to this, if we delay sending the view distance change by a second or more the entities show up just fine.

Build 15 has this fix in it.

Any new issues, go ahead and open them on my fork as I'll be maintaining it for a while.

**Comment by sofianedjerbi** [comment]
Fixed in 337dde5
